name: Docker Hub-a Avtomatik Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      # 1. Kodları bulud kompüterinə yüklə
      - name: Kodları götür
        uses: actions/checkout@v4

      # 2. Docker Hub-a daxil ol (Login)
      - name: Docker Hub-a Login Ol
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      # 3. Image-i yığ və avtomatik Docker Hub-a göndər (Push)
      - name: Build və Push
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/cicd-test:latest
